eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint: http://PAYMENT-SERVICE/payment/save
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nikhil_local_db
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update  
